name: tic_tac_toe.server

dependencies:
  tic_tac_toe.net:
    path: ../net
  tic_tac_toe.state:
    path: ../state
  tic_tac_toe.database:
    path: ../database
  express:
  fixnum:
  distributed:
    git: git://github.com/kharland/distributed_dart.git
dev_dependencies:
  test:
  mockito:
